//Types for HomePage actions and reducers
export const STORE_LIST_REQUESTED = "STORE_LIST_REQUESTED";
export const STORE_LIST_SUCCESS = "STORE_LIST_SUCCESS";
export const STORE_LIST_FAILED = "STORE_LIST_FAILED";
export const STORE_COUPON_REQUESTED =  "STORE_COUPON_REQUESTED";
export const STORE_COUPON_SUCCESS =  "STORE_COUPON_SUCCESS";
export const STORE_COUPON_FAILED =  "STORE_COUPON_REQUESTED";
export const SEARCH_INPUT_CHANGE = "SEARCH_INPUT_CHANGE"; 